-- Empty Oracle's recycle bin and disable the recycle bin for the session
PURGE recyclebin;
ALTER SESSION SET recyclebin = OFF;
-- ALTER SESSION SET recyclebin = ON;

DROP VIEW Buchungssicht;
DROP VIEW Reservierungssicht;
DROP VIEW Familienwohnung;
DROP VIEW UebersichtKunden;
DROP VIEW Zahlungsstatus;
DROP VIEW MidAgeKunden;
DROP TABLE ENTFERNUNG;
DROP TABLE VERBINDEN;
DROP TABLE BEINHALTEN;
DROP TABLE BILDER;
DROP TABLE TOURISTENATTRAKTION;

ALTER TABLE ADRESSE 
DROP CONSTRAINT Adresse_Ort;

DROP TABLE ORT;
DROP TABLE FLUGHAFEN;
DROP TABLE RECHNUNG;
DROP TABLE BELEGUNG;
DROP TABLE KUNDE;
DROP TABLE FERIENWOHNUNG;
DROP TABLE ADRESSE;
DROP TABLE ZUSATZAUSSTATTUNG;
DROP TABLE LAND;
DROP TABLE FLUGGESELLSCHAFT;
DROP TABLE BANKVERBINDUNG;