
DELETE FROM ENTFERNUNG;
DELETE FROM VERBINDEN;
DELETE FROM BEINHALTEN;
DELETE FROM BILDER;
DELETE FROM TOURISTENATTRAKTION;
DELETE FROM ORT;
DELETE FROM FLUGHAFEN;
DELETE FROM RECHNUNG;
DELETE FROM BELEGUNG;
DELETE FROM KUNDE;
DELETE FROM FERIENWOHNUNG;
DELETE FROM ADRESSE;
DELETE FROM ZUSATZAUSSTATTUNG;
DELETE FROM LAND;
DELETE FROM FLUGGESELLSCHAFT;
DELETE FROM BANKVERBINDUNG;





COMMIT;